
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
  version: 0.2
  phases:
    install:
      commands:
            - echo update npm...
            - npm install -g n
            - n latest
            - npm update -g npm
            - echo node -v
            - node -v
            - echo npm -v
            - npm -v
            - echo install yarn...
            - npm install -g yarn
            - echo yarn -v
            - yarn -v
    pre_build:
      commands:
        #installs dependencies into the node_modules/ directory
        - echo Entered the pre_build phase...
        - yarn install
    build:
      commands:
        - echo Build started on `date`
        - echo Compiling
        - yarn run build
    post_build:
      commands:
        - echo Build completed on `date`
  # Include only the files required for your application to run.
  artifacts:
    files:
        -   package.json
    base-directory: 
       -  dist
